### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
One thing i haven't look at yet is the idea of using #main

**Comment by Alhadis** [comment]
@wader I've resolved the merge conflicts for you. Since we're introducing loud changes, any chance we could reformat the code to use *tabs* instead of spaces? I only ask because I know this repo was [generated by Atom's grammar converter](https://flight-manual.atom.io/hacking-atom/sections/converting-from-textmate/), which formats the results using Atom/GitHub's preferred coding style, rather than the user's (which, for a _text editor_, is a big no-no). Hence, the use of 2-space indents and quoted keys is rarely a decision by the user who originally generated it.

> One thing i haven't look at yet is the idea of using #main

I took care of that too. 👍

**Comment by wader** [comment]
👍  Thanks! yes go ahead a change to tabs. I tried but wasn't sure if you want purely tabs or some mix in some case like the multiline strings etc.

**Comment by wader** [comment]
Feel free to merge when your done

**Comment by Alhadis** [comment]
Done. 👍

>  I tried but wasn't sure if you want purely tabs or some mix in some case like the multiline strings etc.

Nope, I [always](https://github.com/Alhadis/Coding-Style) use tabs to indent, spaces to align, and always separated from each other by at least one visible (non-whitespace) character. Moreover, I avoid increasing indentation depth by more than one level.

I've also reordered some of the properties so `name` comes first, and `begin`/`end` and `beginCaptures`/`endCaptures` are grouped. Atom's grammar converter sorts each field alphabetically, burying arguably more relevant fields below (potentially) very long ones.

**Pull request merged**
